### ISSUE TITLE
AssertionError: Error: wrong input BEGIN IONS

### ISSUE THREAD

**Issue by denisbeslic** [volpato30/PointNovo#2]
Dear author,

I tried to train PointNovo on a mgf file, but encountered following error:

```
CUDA_VISIBLE_DEVICES=3 make train
python main.py --train
Training vocab_reverse  ['_PAD', '_GO', '_EOS', 'A', 'R', 'N', 'N(Deamidation)', 'D', 'C(Carbamidomethylation)', 'E', 'Q', 'Q(Deamidation)', 'G', 'H', 'I', 'L', 'K', 'M', 'M(Oxidation)', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']
Training vocab  {'_PAD': 0, '_GO': 1, '_EOS': 2, 'A': 3, 'R': 4, 'N': 5, 'N(Deamidation)': 6, 'D': 7, 'C(Carbamidomethylation)': 8, 'E': 9, 'Q': 10, 'Q(Deamidation)': 11, 'G': 12, 'H': 13, 'I': 14, 'L': 15, 'K': 16, 'M': 17, 'M(Oxidation)': 18, 'F': 19, 'P': 20, 'S': 21, 'T': 22, 'W': 23, 'Y': 24, 'V': 25}
Training vocab_size  26
MAX_LEN  30
num_ion  12
weight_decay  0.0
embedding_size  512
num_lstm_layers  1
num_units  64
batch_size  16
steps_per_validation  300
max_gradient_norm  5.0
2021-05-26 17:41:05,344 [INFO] __main__: training mode
2021-05-26 17:41:05,344 [INFO] data_reader: input spectrum file: /home/dbeslic/master/DeepLearning_TrainingData/02_NISTmAb/ONLY_NistMab/spectrum.mgf
2021-05-26 17:41:05,344 [INFO] data_reader: input feature file: /home/dbeslic/master/DeepLearning_TrainingData/02_NISTmAb/ONLY_NistMab/features.train.csv
2021-05-26 17:41:05,344 [INFO] data_reader: read cached spectrum locations
2021-05-26 17:41:05,569 [INFO] data_reader: read 6059 features, 3316 skipped by mass, 0 skipped by unknown modification, 0 skipped by length
2021-05-26 17:41:05,569 [INFO] train_func: 378 steps per epoch
2021-05-26 17:41:05,569 [INFO] data_reader: input spectrum file: /home/dbeslic/master/DeepLearning_TrainingData/02_NISTmAb/ONLY_NistMab/spectrum.mgf
2021-05-26 17:41:05,569 [INFO] data_reader: input feature file: /home/dbeslic/master/DeepLearning_TrainingData/02_NISTmAb/ONLY_NistMab/features.valid.csv
2021-05-26 17:41:05,569 [INFO] data_reader: read cached spectrum locations
2021-05-26 17:41:05,593 [INFO] data_reader: read 687 features, 297 skipped by mass, 0 skipped by unknown modification, 0 skipped by length
2021-05-26 17:41:05,599 [INFO] train_func: initialize a set of new parameters
Traceback (most recent call last):
  File "main.py", line 133, in <module>
    main()
  File "main.py", line 24, in main
    train()
  File "/home/dbeslic/master/antibody-de-novo-sequencing/resources/PointNovo/train_func.py", line 230, in train
    for i, data in enumerate(train_data_loader):
  File "/home/dbeslic/.conda/envs/pointnovo/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/dbeslic/.conda/envs/pointnovo/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/dbeslic/.conda/envs/pointnovo/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/dbeslic/.conda/envs/pointnovo/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dbeslic/.conda/envs/pointnovo/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dbeslic/.conda/envs/pointnovo/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dbeslic/.conda/envs/pointnovo/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dbeslic/master/antibody-de-novo-sequencing/resources/PointNovo/data_reader.py", line 223, in __getitem__
    return self._get_feature(feature)
  File "/home/dbeslic/master/antibody-de-novo-sequencing/resources/PointNovo/data_reader.py", line 233, in _get_feature
    assert "BEGIN IONS" in line, "Error: wrong input BEGIN IONS"
AssertionError: Error: wrong input BEGIN IONS
```

Do you have an idea what could cause such an error? 

The algorithms works on the data you provided (ABRF).

**Comment by volpato30** [comment]
PointNovo internally assumes a certain set of headers for the mgf file. Check https://github.com/volpato30/PointNovo/blob/552b09a0923d3b89d73b9f4628b3495c145acd7f/data_reader.py#L231

Basically, it assumes for each spectrum the headers come in the following order: BEGIN IONS, TITLE, PEPMASS, CHARGE, SCANS, RTINSECONDS. 

You can change lines 231-242 of the data_reader.py file so that it supports the mgf file that you are using.
